### PR TITLE
Removed using anchor tags to scroll to footer and top of home page.

### PR DESCRIPTION
**Pull request by ctwoolsey**
Created scrolling directive
Fixed ticketFinder boxes not scrolling all the way to bottom when they are opened.

### CODE REVIEW

**Comment by ctwoolsey** [comment]
Will, the problem is that if I use anchorScroll directly, it will scroll but do it before the component has fully been rendered.  So I'm left with an incomplete scroll.  This was the problem that was happening on the current site using anchor tags.  The ticketInfoBoxes use an ng-include inside of them.  This material didn't get rendered before the scroll happened.  So the page would scroll correctly, but then the material would render and the end result would be the bottom of the expanded box would be hidden below screen.

**Comment by wstampley** [comment]
Seems like you need a callback after render. Does this solution work because it gets rid of the race you talk about above (scrolling before rendering everything) or does it work because of the 500ms timeout you have delaying the scroll?

**Comment by ctwoolsey** [comment]
It works because of the 500ms timeout.  I couldn't find an event that triggered on the rendering being complete. Even though a number of the events I tried, seemed to claim that they would trigger on rendering complete.

**Comment by ctwoolsey** [comment]
So I modified the code a little, but it still needs the timeout.  The event, $includeContentLoaded fires, before the DOM is updated and needs a timeout with a delay.

**Comment by wstampley** [comment]
Well, I know solutions for this in other frameworks but nothing specifically for Angular. @abobwhite - any thoughts or is this good?

**Comment by abobwhite** [comment]
Uh...this code appears to be already in another PR in another branch....

**Comment by ctwoolsey** [comment]
Yes, When I wrote the back-button PR, I built it off of this change.  Ideally, this was supposed to get merged first, then I'd take the back-button-2 PR merge it with develop and the changes wouldn't appear in back-button-2.  Initially my back-button PR needed these changes.

**Comment by abobwhite** [comment]
I'm not too thrilled about adding all this code just to handle some scrolling but if this is what they want, then so be it. I don't have any other solutions off hand. 

I approve but there was a small area where the if/else could have been trimmed up by just relying on the variable you were setting to true/false and just return that variable vs two returns. It's just a stylistic and simplification thing so no big deal.

**Pull request merged**
